### ISSUE TITLE
twitter timeline integration

### ISSUE THREAD

**Issue by thekeele** [thekeele/sentweet#11]
add integration to POST _hello world_ to the bitfeels bot twitter timeline

prerequisite work for #15 

POST tweet
https://developer.twitter.com/en/docs/tweets/post-and-engage/api-reference/post-statuses-update

Will need credentials for the account we're posting to. This will be different that the stream credentials.

Request Example
```
curl -XPOST 
  --url 'https://api.twitter.com/1.1/statuses/update.json?status=hello' 
  --header 'authorization: OAuth
  oauth_consumer_key="oauth_customer_key",
  oauth_nonce="generated_oauth_nonce",
  oauth_signature="generated_oauth_signature",
  oauth_signature_method="HMAC-SHA1",
  oauth_timestamp="generated_timestamp",
  oauth_token="oauth_token",
  oauth_version="1.0"'
```

**Comment by thekeele** [comment]
<img width="592" alt="twitter_post" src="https://user-images.githubusercontent.com/5237832/85650715-18fe4500-b674-11ea-9dba-b67168f8e731.png">
@rcehemann

**Comment by rcehemann** [comment]
:fire: :boom: :1st_place_medal:

**Comment by thekeele** [comment]
<img width="604" alt="Screen Shot 2020-06-25 at 11 41 28 PM" src="https://user-images.githubusercontent.com/5237832/85817815-1a477480-b73d-11ea-8480-c0009f7c9562.png">
@rcehemann 😎 🚀 🔥
